# -*- coding: utf-8 -*-
"""Auto Tagging Support Tickets Using LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10hwwJILvTz17-bj7XrRi-urmXaawhSXG

# Task 5: Auto Tagging Support Tickets Using LLM
### DevelopersHub Corporation – AI/ML Engineering Internship
**Objective:** Automatically tag support tickets using prompt engineering (zero-shot & few-shot)
with Groq LLM, fine-tune DistilBERT for comparison, and output top 3 tags per ticket.
"""

!pip install groq transformers datasets scikit-learn pandas numpy matplotlib seaborn torch -q

"""Imports & Groq Setup"""

import os
import json
import re
import time
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch
warnings.filterwarnings("ignore")

from groq import Groq
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

# ✅ Paste your Groq API key here
GROQ_API_KEY = "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"
client = Groq(api_key=GROQ_API_KEY)

GROQ_MODEL = "llama-3.1-8b-instant"   # ← CHANGED THIS LINE

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Groq model : {GROQ_MODEL}")
print(f"Device     : {device}")
print("✅ Setup complete")

"""Load & Prepare Dataset"""

from datasets import load_dataset

# Define tags first
TAGS = [
    'Billing and Payments',
    'Customer Service',
    'IT Support',
    'Product Support',
    'Technical Support'
]

print("Loading dataset from HuggingFace...")
raw = load_dataset("Tobi-Bueck/customer-support-tickets", split="train")
df_raw = raw.to_pandas()

print(f"Raw dataset shape : {df_raw.shape}")
print(f"Columns           : {df_raw.columns.tolist()}")
print(f"\nLanguage distribution:")
print(df_raw['language'].value_counts().head())

"""Clean & Sample Exactly 50 Tickets"""

# Keep English only
df_en = df_raw[df_raw['language'] == 'en'].copy()
print(f"English tickets: {len(df_en)}")

# Combine subject + body as ticket text
df_en['ticket_text'] = df_en['subject'].fillna('') + ' ' + df_en['body'].fillna('')
df_en['ticket_text'] = df_en['ticket_text'].str.strip()
df_en['true_label'] = df_en['queue']

print(f"\nAll queue labels:")
print(df_en['true_label'].value_counts())

# Keep only our 5 target categories
df_filtered = df_en[df_en['true_label'].isin(TAGS)].copy()
print(f"\nFiltered size: {len(df_filtered)}")

# Sample exactly 10 per category = 50 total
samples = []
for tag in TAGS:
    tag_df = df_filtered[df_filtered['true_label'] == tag].copy()
    sampled = tag_df.sample(min(10, len(tag_df)), random_state=42)
    samples.append(sampled)

df = pd.concat(samples).reset_index(drop=True)
df = df[['ticket_text', 'true_label']].dropna().reset_index(drop=True)
df['ticket_id'] = range(1, len(df) + 1)

print(f"\nFinal dataset size : {len(df)}")
print(f"Class distribution :")
print(df['true_label'].value_counts())
print(f"\nSample ticket:")
print(df['ticket_text'][0][:200])

"""EDA"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

colors = ['#2196F3', '#4CAF50', '#FF9800', '#E91E63', '#9C27B0']

df['true_label'].value_counts().plot(
    kind='bar', ax=axes[0], color=colors, edgecolor='black'
)
axes[0].set_title('Ticket Category Distribution', fontweight='bold')
axes[0].set_xlabel('Category')
axes[0].set_ylabel('Count')
axes[0].tick_params(rotation=25)

df['text_length'] = df['ticket_text'].apply(len)
axes[1].hist(df['text_length'], bins=15, color='#2196F3', edgecolor='black', alpha=0.8)
axes[1].set_title('Ticket Text Length Distribution', fontweight='bold')
axes[1].set_xlabel('Character Count')
axes[1].set_ylabel('Frequency')

plt.tight_layout()
plt.savefig('eda.png', dpi=150)
plt.show()

print(f"Average ticket length: {df['text_length'].mean():.0f} characters")

"""Zero-Shot Classification Function"""

def zero_shot_classify(ticket_text, top_k=3):
    """Zero-Shot: No examples in prompt. LLM classifies purely from instruction."""
    prompt = f"""You are a customer support ticket classifier.

Classify the following support ticket into ONE of these exact categories:
- Billing and Payments
- Customer Service
- IT Support
- Product Support
- Technical Support

Return a JSON object with this exact format:
{{
  "top1": {{"tag": "category_name", "confidence": 0.95}},
  "top2": {{"tag": "category_name", "confidence": 0.03}},
  "top3": {{"tag": "category_name", "confidence": 0.02}}
}}

Rules:
- tag values must exactly match one of the 5 category names listed above
- top1 is your best prediction
- top2 and top3 must be different from top1 and each other
- confidences must sum to 1.0
- Return ONLY the JSON, nothing else

Support Ticket: "{ticket_text[:300]}"
"""
    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=200
        )
        raw = response.choices[0].message.content.strip()
        match = re.search(r'\{.*\}', raw, re.DOTALL)
        if match:
            result = json.loads(match.group())
            top1 = result['top1']['tag']
            top2 = result['top2']['tag']
            top3 = result['top3']['tag']
            s1 = result['top1']['confidence']
            s2 = result['top2']['confidence']
            s3 = result['top3']['confidence']
            return [top1, top2, top3], [s1, s2, s3]
    except Exception as e:
        print(f"  Warning: {e}")
    return [TAGS[0], TAGS[1], TAGS[2]], [0.6, 0.3, 0.1]

# Test on single ticket
text = df['ticket_text'][0]
labels, scores = zero_shot_classify(text)
print("=== ZERO-SHOT SINGLE TEST ===")
print(f"Ticket : {text[:150]}")
print(f"Top 1  : {labels[0]} ({scores[0]*100:.1f}%)")
print(f"Top 2  : {labels[1]} ({scores[1]*100:.1f}%)")
print(f"Top 3  : {labels[2]} ({scores[2]*100:.1f}%)")

"""Run Zero-Shot on All 50 Tickets"""

print("Running Zero-Shot on all 50 tickets...")
print("(~1 second per ticket)\n")

zs_results = []
for i in range(len(df)):
    row = df.iloc[i]
    labels, scores = zero_shot_classify(row['ticket_text'])
    zs_results.append({
        'ticket_id'  : row['ticket_id'],
        'ticket_text': row['ticket_text'][:60] + '...',
        'true_label' : row['true_label'],
        'top1_tag'   : labels[0], 'top1_score': round(scores[0]*100, 1),
        'top2_tag'   : labels[1], 'top2_score': round(scores[1]*100, 1),
        'top3_tag'   : labels[2], 'top3_score': round(scores[2]*100, 1),
        'correct'    : labels[0] == row['true_label']
    })
    time.sleep(0.5)
    if (i + 1) % 10 == 0:
        print(f"  Processed {i+1}/{len(df)} tickets")

zs_df = pd.DataFrame(zs_results)
zs_acc = accuracy_score(zs_df['true_label'], zs_df['top1_tag'])
zs_f1  = f1_score(zs_df['true_label'], zs_df['top1_tag'], average='weighted')

print(f"\n=== ZERO-SHOT RESULTS ===")
print(f"Accuracy : {zs_acc*100:.2f}%")
print(f"F1 Score : {zs_f1:.4f}")
print(f"Correct  : {zs_df['correct'].sum()}/{len(df)}")

"""Few-Shot Classification Function"""

def few_shot_classify(ticket_text, top_k=3):
    """Few-Shot: 5 labeled examples in prompt, one per category."""
    prompt = f"""You are a customer support ticket classifier.

Here are labeled examples to guide your classification:

Example 1:
Ticket: "I was charged twice this month and need a refund immediately."
Category: Billing and Payments

Example 2:
Ticket: "I am unhappy with the service I received and want to give feedback."
Category: Customer Service

Example 3:
Ticket: "My computer cannot connect to the company VPN after the update."
Category: IT Support

Example 4:
Ticket: "The product I received stopped working after two days of use."
Category: Product Support

Example 5:
Ticket: "The application keeps crashing whenever I try to export a file."
Category: Technical Support

Now classify the ticket below into ONE of these exact categories:
- Billing and Payments
- Customer Service
- IT Support
- Product Support
- Technical Support

Return a JSON object with this exact format:
{{
  "top1": {{"tag": "category_name", "confidence": 0.95}},
  "top2": {{"tag": "category_name", "confidence": 0.03}},
  "top3": {{"tag": "category_name", "confidence": 0.02}}
}}

Rules:
- tag values must exactly match one of the 5 category names listed above
- top1 is your best prediction
- top2 and top3 must be different from top1 and each other
- confidences must sum to 1.0
- Return ONLY the JSON, nothing else

Support Ticket: "{ticket_text[:300]}"
"""
    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=200
        )
        raw = response.choices[0].message.content.strip()
        match = re.search(r'\{.*\}', raw, re.DOTALL)
        if match:
            result = json.loads(match.group())
            top1 = result['top1']['tag']
            top2 = result['top2']['tag']
            top3 = result['top3']['tag']
            s1 = result['top1']['confidence']
            s2 = result['top2']['confidence']
            s3 = result['top3']['confidence']
            return [top1, top2, top3], [s1, s2, s3]
    except Exception as e:
        print(f"  Warning: {e}")
    return [TAGS[0], TAGS[1], TAGS[2]], [0.6, 0.3, 0.1]

# Test on single ticket
labels, scores = few_shot_classify(df['ticket_text'][0])
print("=== FEW-SHOT SINGLE TEST ===")
print(f"Ticket : {df['ticket_text'][0][:150]}")
print(f"Top 1  : {labels[0]} ({scores[0]*100:.1f}%)")
print(f"Top 2  : {labels[1]} ({scores[1]*100:.1f}%)")
print(f"Top 3  : {labels[2]} ({scores[2]*100:.1f}%)")

"""Run Few-Shot on All 50 Tickets"""

print("Running Few-Shot on all 50 tickets...")
print("(~1 second per ticket)\n")

fs_results = []
for i in range(len(df)):
    row = df.iloc[i]
    labels, scores = few_shot_classify(row['ticket_text'])
    fs_results.append({
        'ticket_id'  : row['ticket_id'],
        'ticket_text': row['ticket_text'][:60] + '...',
        'true_label' : row['true_label'],
        'top1_tag'   : labels[0], 'top1_score': round(scores[0]*100, 1),
        'top2_tag'   : labels[1], 'top2_score': round(scores[1]*100, 1),
        'top3_tag'   : labels[2], 'top3_score': round(scores[2]*100, 1),
        'correct'    : labels[0] == row['true_label']
    })
    time.sleep(0.5)
    if (i + 1) % 10 == 0:
        print(f"  Processed {i+1}/{len(df)} tickets")

fs_df = pd.DataFrame(fs_results)
fs_acc = accuracy_score(fs_df['true_label'], fs_df['top1_tag'])
fs_f1  = f1_score(fs_df['true_label'], fs_df['top1_tag'], average='weighted')

print(f"\n=== FEW-SHOT RESULTS ===")
print(f"Accuracy : {fs_acc*100:.2f}%")
print(f"F1 Score : {fs_f1:.4f}")
print(f"Correct  : {fs_df['correct'].sum()}/{len(df)}")

"""Fine-Tune DistilBERT"""

from transformers import (
    DistilBertTokenizer,
    DistilBertForSequenceClassification,
    Trainer, TrainingArguments,
    DataCollatorWithPadding
)
from datasets import Dataset

# Label encoding
label2id = {tag: i for i, tag in enumerate(TAGS)}
id2label = {i: tag for i, tag in enumerate(TAGS)}

# Encode labels
df['label'] = df['true_label'].map(label2id)

# Train/test split
train_df, test_df = train_test_split(
    df[['ticket_text', 'label']],
    test_size=0.2,
    random_state=42,
    stratify=df['label']
)

train_df = train_df.reset_index(drop=True)
test_df  = test_df.reset_index(drop=True)

print(f"Train size : {len(train_df)}")
print(f"Test size  : {len(test_df)}")

# Tokenize
ft_tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")

def tokenize(examples):
    return ft_tokenizer(
        examples["ticket_text"],
        truncation=True,
        padding=False,
        max_length=128
    )

train_dataset = Dataset.from_pandas(train_df)
test_dataset  = Dataset.from_pandas(test_df)

train_tokenized = train_dataset.map(tokenize, batched=True, remove_columns=["ticket_text"])
test_tokenized  = test_dataset.map(tokenize, batched=True, remove_columns=["ticket_text"])

print("✅ Tokenization complete")
print(f"Columns: {train_tokenized.column_names}")

"""Train DistilBERT"""

ft_model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=len(TAGS),
    id2label=id2label,
    label2id=label2id
)

data_collator = DataCollatorWithPadding(tokenizer=ft_tokenizer)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "f1"      : f1_score(labels, preds, average='weighted')
    }

training_args = TrainingArguments(
    output_dir               = "./distilbert-tickets",
    num_train_epochs         = 10,
    per_device_train_batch_size = 8,
    per_device_eval_batch_size  = 8,
    warmup_steps             = 10,
    weight_decay             = 0.01,
    learning_rate            = 3e-5,
    eval_strategy            = "epoch",
    save_strategy            = "epoch",
    load_best_model_at_end   = True,
    metric_for_best_model    = "f1",
    logging_steps            = 5,
    report_to                = "none",
    fp16                     = torch.cuda.is_available()
)

trainer = Trainer(
    model            = ft_model,
    args             = training_args,
    train_dataset    = train_tokenized,
    eval_dataset     = test_tokenized,
    processing_class = ft_tokenizer,
    data_collator    = data_collator,
    compute_metrics  = compute_metrics
)

print("Starting DistilBERT fine-tuning...")
print("=" * 50)
trainer.train()
print("\n✅ Fine-tuning complete!")

"""Evaluate Fine-Tuned Model"""

ft_eval = trainer.evaluate()
ft_acc  = ft_eval['eval_accuracy']
ft_f1   = ft_eval['eval_f1']

print("=" * 50)
print("FINE-TUNED DISTILBERT RESULTS")
print("=" * 50)
print(f"Accuracy : {ft_acc*100:.2f}%")
print(f"F1 Score : {ft_f1:.4f}")

# Get top-3 predictions
ft_output  = trainer.predict(test_tokenized)
ft_logits  = ft_output.predictions
ft_probs   = torch.softmax(torch.tensor(ft_logits), dim=-1).numpy()
ft_top3    = np.argsort(ft_probs, axis=-1)[:, ::-1][:, :3]
ft_true    = ft_output.label_ids

print(f"\nDetailed Report:")
print(classification_report(
    ft_true,
    ft_top3[:, 0],
    target_names=TAGS
))

"""Full Comparison"""

comparison = pd.DataFrame({
    'Approach'       : ['Zero-Shot (LLaMA3)', 'Few-Shot (LLaMA3)', 'Fine-Tuned (DistilBERT)'],
    'Accuracy (%)'   : [round(zs_acc*100, 2), round(fs_acc*100, 2), round(ft_acc*100, 2)],
    'F1 Score'       : [round(zs_f1, 4), round(fs_f1, 4), round(ft_f1, 4)],
    'Needs Training' : ['No', 'No', 'Yes'],
    'Needs API Key'  : ['Yes', 'Yes', 'No']
})

print("=" * 65)
print("FULL COMPARISON: ZERO-SHOT vs FEW-SHOT vs FINE-TUNED")
print("=" * 65)
print(comparison.to_string(index=False))

# Bar charts
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
approaches = ['Zero-Shot\n(LLaMA3)', 'Few-Shot\n(LLaMA3)', 'Fine-Tuned\n(DistilBERT)']
accs = [zs_acc*100, fs_acc*100, ft_acc*100]
f1s  = [zs_f1*100,  fs_f1*100,  ft_f1*100]
cols = ['#2196F3', '#4CAF50', '#FF9800']

for ax, values, title, ylabel in zip(
    axes,
    [accs, f1s],
    ['Accuracy Comparison', 'F1 Score Comparison'],
    ['Accuracy (%)', 'F1 Score (%)']
):
    bars = ax.bar(approaches, values, color=cols, edgecolor='black', width=0.5)
    ax.set_title(title, fontweight='bold', fontsize=13)
    ax.set_ylabel(ylabel)
    ax.set_ylim(0, 110)
    for bar, val in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width()/2,
                bar.get_height() + 1.5,
                f'{val:.1f}%', ha='center', fontweight='bold')

plt.suptitle('Approach Comparison — Task 5', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('comparison_chart.png', dpi=150)
plt.show()

"""Confusion Matrices"""

fig, axes = plt.subplots(1, 3, figsize=(22, 6))

short_tags = ['Billing', 'Customer\nService', 'IT\nSupport', 'Product\nSupport', 'Technical\nSupport']

ft_true_labels = [id2label[i] for i in ft_true]
ft_pred_labels = [id2label[i] for i in ft_top3[:, 0]]

datasets = [
    (zs_df['true_label'].tolist(), zs_df['top1_tag'].tolist(), 'Zero-Shot (LLaMA3)'),
    (fs_df['true_label'].tolist(), fs_df['top1_tag'].tolist(), 'Few-Shot (LLaMA3)'),
    (ft_true_labels, ft_pred_labels, 'Fine-Tuned (DistilBERT)')
]

for ax, (true, pred, title) in zip(axes, datasets):
    cm = confusion_matrix(true, pred, labels=TAGS)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
                xticklabels=short_tags, yticklabels=short_tags)
    ax.set_title(title, fontweight='bold')
    ax.set_ylabel('True')
    ax.set_xlabel('Predicted')

plt.tight_layout()
plt.savefig('confusion_matrices.png', dpi=150)
plt.show()

"""Top 3 Tags Final Output"""

print("=" * 70)
print("FINAL OUTPUT — TOP 3 PREDICTED TAGS PER TICKET (Zero-Shot)")
print("=" * 70)

for _, row in zs_df.iterrows():
    status = "✅" if row['correct'] else "❌"
    print(f"\n[#{int(row['ticket_id'])}] {status}  True: {row['true_label']}")
    print(f"  Text : {row['ticket_text']}")
    print(f"  Tag 1: {row['top1_tag']:<25} ({row['top1_score']}%)")
    print(f"  Tag 2: {row['top2_tag']:<25} ({row['top2_score']}%)")
    print(f"  Tag 3: {row['top3_tag']:<25} ({row['top3_score']}%)")